server:
  port: 4444
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled:  true
          lower-case-service-id: true
      routes:
      - id: one
        uri: lb://WELCOME-API
        predicates:
        - Path=/wish
      - id: two
        uri: lb://HELLO-API
        predicates:
        - Path=/hello
                
  application:
    name: API-GATEWAY      
    
    
eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka/
      
     