server:
  port: 7070
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: one
        uri: lb://WELCOME-API
        predicates:
        - Path=/welcome
        
      - id: two
        uri: lb://GREET-API
        predicates:
        - Path=/greet
          
      
        
          
              