server:
  port: 3333
  
spring:
  application:
    name: HELLO-API
    
    
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
    
eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'     
      