server:
  port: 2222
  
eureka:
  client:
    service-url:
      deafultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: WELCOME-API
    
  boot:
    admin:
      client:
        url:
        - http://localhost:1111/
    
management:
  endpoints:
    web:
      exposure:
        include: '*'    
        